// Token build: DTCG tokens.json -> Style Dictionary v5 -> Tailwind v4 `@theme` CSS.
// Run: pnpm tokens:build
import StyleDictionary from 'style-dictionary';

/**
 * Custom format: emits a Tailwind v4 theme file.
 *  - semantic.light.* -> `@theme { --color-<name>: <oklch> }`  (generates utilities + :root vars)
 *  - semantic.dark.*  -> `.dark { --color-<name>: <oklch> }`    (runtime re-theme, no JS)
 *  - radius.*         -> `--radius`
 * oklch values pass through untouched (no color transform) so theming stays perceptual
 * and tweakcn output drops in unchanged.
 */
StyleDictionary.registerFormat({
  name: 'tailwind-v4',
  format: ({ dictionary }) => {
    const light = [];
    const dark = [];
    const root = [];

    for (const token of dictionary.allTokens) {
      const value = token.value ?? token.$value;
      const [group, mode, ...rest] = token.path;
      if (group === 'semantic' && mode === 'light') {
        light.push(`  --color-${rest.join('-')}: ${value};`);
      } else if (group === 'semantic' && mode === 'dark') {
        dark.push(`  --color-${rest.join('-')}: ${value};`);
      } else if (group === 'radius') {
        root.push(`  --radius: ${value};`);
      }
    }

    return [
      '/* AUTO-GENERATED by tokens/build.mjs — do not edit by hand. Source: tokens/tokens.json */',
      '@import "tailwindcss";',
      '',
      '@custom-variant dark (&:is(.dark *));',
      '',
      '@theme {',
      ...light,
      ...root,
      '}',
      '',
      '.dark {',
      ...dark,
      '}',
      '',
    ].join('\n');
  },
});

const sd = new StyleDictionary({
  source: ['tokens/tokens.json'],
  usesDtcg: true,
  platforms: {
    css: {
      transforms: [],
      buildPath: 'tokens/dist/',
      files: [{ destination: 'theme.css', format: 'tailwind-v4' }],
    },
  },
});

await sd.buildAllPlatforms();
console.log('✔ tokens -> tokens/dist/theme.css');
